# Permalinks
permalink:           posts/:year/:month/:day/:title

# Setup
title:               The @AALLWestPac Source
tagline:             Announcements for the Western Pacific Chapter of AALL
url:                 https://aallwestpac.github.io
paginate:            5
paginate_path:       "/updates/page:num/"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              AALL WestPac
  url:               http://chapters.aallnet.org/westpac/
  email:             aallwestpac@gmail.com

# Custom vars
version:             0.1.2
github:
  repo:              https://github.com/aallwestpac/aallwestpac.github.io

# Image location for gDocs Gabriel add-on.
post_assets: assets/posts

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-tweetsert


# From https://github.com/ibrado/jekyll-tweetsert – details in gDrive document
tweetsert:
  enabled: true
  layout: "post"
  debug: false

  title:
    prefix: "[Tweet] "
    words:  11
    suffix: " ..."

  properties:
    is_tweet: true
    tweet_html: $
    share: false
    comments: false

  timeline:
    handle: 'aallwestpac'

    access_token: "2749460815-RsX28C2YhGRDQOqenm6x0Tf5W2xETkwzWip3MNr"
    limit: 100

    replies: false
    retweets: false

    include:
      - '@aallwestpac'
      - '#aallwestpac'

    no_newer: false
    no_older: false

  embed:
    excerpts: true
    theme: "dark"
    link_color: "#2e6690"
    omit_script: false
    prefix: '<em>Tweeted on {{date}}</em>'
    suffix: '<p class="smallPrint">Click <a href="{{url}}">here</a> to comment.</p>'

  category:
    default: "twitter"

    layout: "category_index"
    title:
      prefix: "Posts in the &laquo;"
      suffix: "&raquo; category"

  tags:
    default: "tweet"
    dir: "tag"

    layout: "tag_index"
    title:
      prefix: "Posts tagged &ldquo;"
      suffix: "&rdquo;"

    hashtags: true
#    ignore:
#      - "blahblah"
